### ISSUE TITLE
XML upload not working on windows

### ISSUE THREAD

**Issue by dslosky-usgs** [klin-usgs/shakecast_v4#61]

**Comment by dslosky-usgs** [comment]
Being caused by the semi-odd behavior of backslashes described here:
https://pythonconquerstheuniverse.wordpress.com/2008/06/04/gotcha-%E2%80%94-backslashes-in-windows-filenames/

**Comment by dslosky** [comment]
Rewrote functions, objects, server,  web server, and ORM to build file paths in a more windows friendly  way.  Also sending file paths to server as raw strings.
